### ISSUE TITLE
Bug - worldScale is not being calculated correctly

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser-ce#15]
If a Sprite's scale is `0.5` and its parent is the `Phaser.World`, its `worldScale` is `0.25`. It should be `0.5` as well.

Richard Davey pointed me to [this](https://github.com/photonstorm/phaser/commit/12ac4cc61cf702893f0a15628027990503e55e76) commit to Phaser V3. It should help resolve the issue.

**Comment by samme** [comment]
<http://phaser.io/sandbox/iHnmnGvX>

**Comment by hexus** [comment]
Samme, that's the sprite scale, not the world scale. :)

**Comment by Peter42** [comment]
I took a look at it and it seems that scale is used twice.
For x:
1. it is assigned to the variable a and then multiplied with pt.a and pt.b
1. it is also used as a factor to the parameter for the set method of worldScale.

same applies to y.

This seems wrong, but I'm not sure. If someone could confirm this, I'll create a pull request.

Snip from file `DisplayObject.js`
```diff
else
{
	// lets do the fast version as we know there is no rotation..
	a  = this.scale.x;
	d  = this.scale.y;

	tx = this.position.x - this.pivot.x * a;
	ty = this.position.y - this.pivot.y * d;

	wt.a  = a  * pt.a;
	wt.b  = a  * pt.b;
	wt.c  = d  * pt.c;
	wt.d  = d  * pt.d;
	wt.tx = tx * pt.a + ty * pt.c + pt.tx;
	wt.ty = tx * pt.b + ty * pt.d + pt.ty;
}

//  Set the World values
this.worldAlpha = this.alpha * p.worldAlpha;
this.worldPosition.set(wt.tx, wt.ty);
-this.worldScale.set(this.scale.x * Math.sqrt(wt.a * wt.a + wt.c * wt.c), this.scale.y * Math.sqrt(wt.b * wt.b + wt.d * wt.d));
+this.worldScale.set( Math.sqrt(wt.a * wt.a + wt.c * wt.c), Math.sqrt(wt.b * wt.b + wt.d * wt.d));
this.worldRotation = Math.atan2(-wt.c, wt.d);
```

BTW: I created another example which shows the bug even better (copied most of it from @samme). [https://phaser.io/sandbox/qIoyYCTd](https://phaser.io/sandbox/qIoyYCTd). I added some rotation and scale only one axis. It's rendered correctly, but `worldScale` is set for both axes. Which is because the scaling is applied twice, before and after rotation.

**Comment by hexus** [comment]
Trying to work out why I got an email for this. Did I make a comment, but it was deleted? :thinking: 

Thanks for looking into this though @Peter42.

**Comment by samme** [comment]
Another test: <http://codepen.io/samme/pen/OmPXmW>
