### ISSUE TITLE
Sprites sharing a texture are distorted when one is filtered

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#153]
![Example](https://cloud.githubusercontent.com/assets/435681/24834506/b4fc4f4e-1c9c-11e7-8b18-1234370ce3f8.png)

* A bug in the API:
  * Phaser version(s): 2.7.6, probably >= 2.7
  * Live example: <http://codepen.io/samme/pen/jBjzGj>
  * Reproduce:
    1. Make 4 sprites with the same image texture
    2. Apply the Grayscale filter to the first sprite
  * What should happen: Sprites have equal dimensions and orientation.
  * What happens instead: First sprite has correct dimensions and orientation. Others are upside-down and half-sized.

Via #39

**Comment by Xan0C** [comment]
I compared phaser-ce and phaser v2.6.2 and the WebGLFilterManager binds a PIXI.FilterTexture in the [popFilter](https://github.com/photonstorm/phaser-ce/blob/master/src/pixi/renderers/webgl/utils/WebGLFilterManager.js#L306) method of the FilterManager.

In v2.6.2 the renderBatch always rebinds the texture, in phaser-ce this doesnt happen so the PIXI.FilterTexture created by the FilterManager is still binded?
Binding the texture evrytime we draw it fixes this, but im not sure if this is the right place to fix it. 
Since the texture only needs to be binded if a filter has been applied?
Not sure if its the actual reason why the distortion happens but it definitely has something to do with it =).

This does also fix #154 but masking is still broken #173
```js
PIXI.WebGLSpriteBatch.prototype.renderBatch = function (texture, size, startIndex) {
    if (size === 0) {
        return;
    }
    var gl = this.gl;
    // check if a texture is dirty..
    if (texture._dirty[gl.id]) {
        if (!this.renderSession.renderer.updateTexture(texture)) {
            //  If updateTexture returns false then we cannot render it, so bail out now
            return;
        }
    }else{
        gl.bindTexture(gl.TEXTURE_2D, texture._glTextures[gl.id]);
    }
    gl.drawElements(gl.TRIANGLES, size * 6, gl.UNSIGNED_SHORT, startIndex * 6 * 2);
    // increment the draw count
    this.renderSession.drawCount++;
};
```
http://codepen.io/Nan0C/pen/ybaJMd
