### ISSUE TITLE
Particle autoAlpha/autoScale duration is half the specified duration

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#160]
* Phaser version(s): 2.6, 2.7
* Live example: <http://codepen.io/samme/pen/OmPdwL>
* Reproduce:
  1. Create an emitter
  2. Call `setAlpha` or `setScale` with a duration, e.g., 10s
  3. Start the emitter
* What should happen: Particle alpha and scale tweens complete after duration has passed
* What happens instead: Particle alpha and scale tweens complete after about duration/2 has passed

**Comment by Peter42** [comment]
1. `update` is called twice on the Particle per frame.
![call1](https://cloud.githubusercontent.com/assets/1571820/25172580/c894e680-24f1-11e7-9f98-b950f6d13e86.PNG)
![call2](https://cloud.githubusercontent.com/assets/1571820/25172592/ccd54b90-24f1-11e7-8168-2bdb722053de.PNG)
1. Inside update the varibles `_s` and `_a`, which are used as index inside `scaleData` and `alphaData`, are decremented
``` javascript
Phaser.Particle.prototype.update = function() {

    if (this.autoScale)
    {
        this._s--;

        if (this._s)
        {
            this.scale.set(this.scaleData[this._s].x, this.scaleData[this._s].y);
        }
        else
        {
            this.autoScale = false;
        }
    }

    if (this.autoAlpha)
    {
        this._a--;

        if (this._a)
        {
            this.alpha = this.alphaData[this._a].v;
        }
        else
        {
            this.autoAlpha = false;
        }
    }

};
```

So in every frame, the variables are decremented twice and the animation gets advanced by two frames.

I see two possible solutions:
* make sure `update` is only called once.
* calculate indices based on the frame number or elapsed time.

I'm not sure which one is the better solution because I'm not familiar enough with the phaser internals.

**Comment by samme** [comment]
Phaser.Particles#update seems redundant. Odd thing is an emitter with `exists=false` gets updated via Stage but not by Particles.

This way skips Particles#update: <http://codepen.io/samme/pen/oWbwwM>
