### ISSUE TITLE
P2 Physics engine - Child Bounding Box has wrong transformation

### ISSUE THREAD

**Issue by linenolte** [photonstorm/phaser-ce#182]
When I add a sprite as child to another child the shape which is used for collision detection is rendered on the wrong position. The position does not consider the transformation of the parent sprite. 

On the screenshot the pentagon is a child of the circle. The shape for the pentagon is on the wrong place. Its on the original position of the pentagon without considering the transformation of the parent,

I use P2 physics engine and version phaser-ce-2.7.6. See the code how to reproduce this behaviour.
A bugfix or an easy workaround would be great. At the moment I do a rought collision detection without the P2 physics engine due to this problem.

thanks a lot 
Holger

![grafik](https://cloud.githubusercontent.com/assets/27810720/25266535/cafbef50-2671-11e7-9756-d5cc7aecefe1.png)

`<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Phaser Hello World</title>
        <script type = "text/javascript" src="./phaser-ce-2.7.6/build/phaser.min.js"></script>

    </head>
    <body>
        <div id="gameContainer" class="game-container"></div>
        <script type="text/javascript">

            var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', {preload: preload, create: create});

            function preload() {
                game.load.image('circle', 'test/images/images.png', 225, 225);
                game.load.image('fuenfeck', 'test/images/fuenfeck.png');
            }

            function create() {

                game.stage.backgroundColor = '#ffffff';

                game.physics.startSystem(Phaser.Physics.P2JS);
                game.physics.p2.gravity.y = 1000;

                sprite1 = game.add.sprite(50, 400, 'fuenfeck');
                sprite1.scale.x = 0.5;
                sprite1.scale.y = 0.5;
                game.physics.p2.enable(sprite1, true);
                sprite1.body.clearShapes();
                sprite1.body.addPolygon({}, 0, 15, 10, 45, 40, 45, 50, 20, 25, 0);
                sprite1.body.data.gravityScale = 0;

                sprite2 = game.add.sprite(100, 200, 'circle');
                sprite2.scale.x = 0.5;
                sprite2.scale.y = 0.5;
                game.physics.p2.enable(sprite2, true);
                sprite2.body.setCircle(45);
                sprite2.body.data.gravityScale = 0;
                sprite2.addChild(sprite1); //here the problem with the wrong position of the pentagon shape is created

            }

        </script>
    </body>
</html>`

**Comment by linenolte** [comment]
I changed my implementation and donnt use nested sprites with P2 physiscs anymore. This works fine for me...

**Comment by flowbytes** [comment]
It looks like the same problem I've described here:
http://www.html5gamedevs.com/topic/35662-p2-physics-child-bug/
Too bad Google did not bring me to this issue before.

My solution was to remove nesting as well and then make a new sprite that follows the quasi-parent by using the update function but it is a somewhat disappointing "solution" since it requires a lot of additional manual handling of killing sprites and getting the collision handler right.

Any ideas where to start looking for this issue?

**Comment by samme** [comment]
Afraid not. 🙁

**Comment by linenolte** [comment]
I did not look deeper into this issue. Removing the parent child relation was easy in my case. I think it is a limitation of the P2 lib.

Regards

Holger

Von meinem Windows Phone gesendet
________________________________
Von: Florian<mailto:notifications@github.com>
Gesendet: ‎10.‎03.‎2018 21:10
An: photonstorm/phaser-ce<mailto:phaser-ce@noreply.github.com>
Cc: Holger<mailto:linenolte@outlook.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [photonstorm/phaser-ce] P2 Physics engine - Child Bounding Box has wrong transformation (#182)


It looks like the same problem I've described here:
http://www.html5gamedevs.com/topic/35662-p2-physics-child-bug/
Too bad Google did not bring me to this issue before.

My solution was to remove nesting as well and then make a new sprite that follows the quasi-parent by using the update function but it is a somewhat disappointing "solution" since it requires a lot of additional manual handling of killing sprites and getting the collision handler right.

Any ideas where to start looking for this issue?

**Comment by ClementRivaille** [comment]
I'm facing this issue as well. And I came to the same conclusion: P2 can't be used with groups, children absolute position and rotation must be calculated manually.

Looking at [World.js](https://github.com/photonstorm/phaser-ce/blob/3845cad6b74ad99e17d6e30641eeedbb5690fc47/src/physics/p2/World.js), the function `enableBody` takes `sprite.x` and `sprite.y` as coordinates. But it might be `sprite.world.x` and `sprite.world.y` instead?
There would still be issues when updating the body position (especially if the group is moving). And for what I've tried, it seems that even `sprite.world` coordinates aren't correct when the sprite is created and added to the group (I had to wait the next frame for it to be updated). There might be a function where the P2 body update its mas center according to the sprite position, and if so it should take its absolute position instead of it relative one. In any case, I guess it's a tricky issue…

Since groups work well for sprites (and maybe other physics engine? Haven't tried them yet), having relative positions for P2 bodies as well should be expected.
