### ISSUE TITLE
Phaser fails to call setResizeCallback on initial load

### ISSUE THREAD

**Issue by LandonSchropp** [photonstorm/phaser-ce#200]
Phaser version(s): 2.7.7
Live example: https://codepen.io/LandonSchropp/pen/PmOpRP?editors=0010

### What Should Happen

When using `Phaser.ScaleManager.RESIZE`, the game has to initially resize the screen to fill the viewport. It should call the resize callback when doing so.

### What Happened Instead

The resize callback was not called. In the example, you can see the console logging `400, 400`, but you don't see it logging the actual size until you resize the container.

**Comment by LandonSchropp** [comment]
Right now I'm working around this issue by using `setTimeout(resize);`. However, I feel like this is a bug that should be fixed.

**Comment by LandonSchropp** [comment]
The `setTimeout` hack doesn't always work as well. There seems to be a race condition that causes that approach to fail every once in a while.

**Comment by samme** [comment]
It does call onResize, exactly once, after scaleMode is changed to RESIZE and without the window being resized: <https://codepen.io/samme/pen/dWZveE>

The game dimensions read in the callback are correct because the canvas and game haven't been resized yet ([Phaser.ScaleManager#setResizeCallback](https://photonstorm.github.io/phaser-ce/Phaser.ScaleManager.html#setResizeCallback)). The `parentBounds` parameter is the important one.

You probably want to use [Phaser.ScaleManager#onSizeChange](https://photonstorm.github.io/phaser-ce/Phaser.ScaleManager.html#onSizeChange) instead.

**Comment by LandonSchropp** [comment]
Yep, that's exactly what I was looking for. I didn't realize there was a different callback. Thanks!
