### ISSUE TITLE
Particle speed lost when using gravity

### ISSUE THREAD

**Issue by Formic** [photonstorm/phaser-ce#203]
This Issue is about (✏️ delete as applicable)

* A bug in the API:
  * Phaser version(s): 2.7.2 +
  * Live example:
      http://phaser.io/examples/v2/particles/click-burst#gv (change to version 2.7.2 or later in drop down (initial load works, you have to change it to something, but then if you change it back to latest it still is broken))
  * What should happen:
      Particles should not stay in starting position
  * What happens instead:
      Particle stay in starting position

**Comment by samme** [comment]
This is because [Emitter#gravity](https://photonstorm.github.io/phaser-ce/Phaser.Particles.Arcade.Emitter.html#gravity) was changed to a Point in 2.7.2 and that change wasn't backwards-compatible. 😢 So it's not exactly a bug but it is a problem.

I think we could replace gravity with a setter that accepts either a number or a Point.

<https://samme.github.io/phaser-examples-mirror/particles/click%20burst.html>

**Comment by Formic** [comment]
@samme Ahh, that makes sense. I use typescript and it's still showing it as a number. I have the latest TS, so that might need an update too? For now I can obviously just use gravity['y'] to set the gravity without having TS show a compile time error.

**Comment by samme** [comment]
I've corrected the type in the master branch.
