### ISSUE TITLE
Game in iframe doesn't resume when refocused (Chrome)

### ISSUE THREAD

**Issue by sergey7c4** [photonstorm/phaser-ce#236]
I used Chrome 58.0.3029.110 (64-bit)
* A bug in the API:
  * Phaser version(s): Phaser CE v2.7.10
  * Live example: [http://plnkr.co/edit/CTDk2k8YHNyyYXvIUBev?p=preview](http://plnkr.co/edit/CTDk2k8YHNyyYXvIUBev?p=preview)
  * What should happen: pause and resume the game
  * What happens instead: game is still paused

**Comment by samme** [comment]
For me the game resumes when refocused in Firefox and Safari, but not in Chrome.

**Comment by AleBles** [comment]
This also happens in older Phaser versions, I usually work around it by setting disableVisibilityChange to true for desktop browsers

**Comment by sergey7c4** [comment]
> This also happens in older Phaser versions

It's true, I think the first bug version is:
v3.0.0 "Shadow Coast" - Built: Wed Sep 21 2016 23:21:07
I'm trying to fix it

**Comment by cokyhe** [comment]
v2.7.3, v2.8.0 also such a bug in chrome, when the game lost focus (for example, click on the page outside the game), will no longer get the focus, the keyboard event all failed. v2.6.2 does not have this bug.

**Comment by samme** [comment]
Please try

```javascript
game.input.mspointer.capture = false;
```

**Comment by sergey7c4** [comment]
> Please try
> game.input.mspointer.capture = false;

It works: [http://plnkr.co/edit/SoUF8cfm13KhppWcqDNk?p=preview](http://plnkr.co/edit/SoUF8cfm13KhppWcqDNk?p=preview)

**Comment by 2called-chaos** [comment]
By the way: I tested a bit around with this issue (so that I might be able to fix the cause)

* Is it correct that mspointer is available in chrome? Phaser.Device says yes because it checks against `window.PointerEvent` which Chrome now has. Even if not, why is capture on by default (is it necessary, mouse has it off by default).
* if your iframe has something non-canvas for you to click on you can unfreeze it that way (also if you go to another tab and come back (I can't tell if this is correct since it blurs the iframe if you click outside of it but give it a focus without the need to click it again)
* The game still does something even if it appears to be frozen (I'm not sure if that is supposed to be like that)
  * Click events are still being registered and my sprite burst will spawn but not move
  * Hover/active states of buttons are triggered, even the associated click event still get's executed
  * My listeners on mouse still fire, keybinds don't

So the fix indeed _is_ to disable MSpointer which shouldn't be active in the first place or is PointerEvent the new thing to use?

**Comment by samme** [comment]
"mspointer" represents the standard PointerEvent too, which Chrome supports. I'd guess capture is on by default in order to [suppress mouse events for the same action](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent#Pointer_event_types) (they would be duplicates).

I think the game is just paused, so you're seeing all `update` calls suspended.

The problem seems to be that Phaser isn't receiving a `focus` event at all while capture is on.

**Comment by samme** [comment]
On <http://plnkr.co/edit/SoUF8cfm13KhppWcqDNk?p=preview>, you can open Chrome's console, select **frame.html**, and run

```javascript
monitor(Phaser.Game.prototype.focusGain);
monitor(Phaser.Game.prototype.focusLoss);
monitor(Phaser.Stage.prototype.visibilityChange);
monitorEvents(window, 'control');
monitorEvents(game.canvas, ['click', 'mouseup', 'pointerup']);
```

**Comment by 2called-chaos** [comment]
> The problem seems to be that Phaser isn't receiving a focus event at all while capture is on.

@samme I mean it might not be the cleanest thing to do but couldn't we/Phaser/mspointer assume that - if you click directly _on_ the canvas - it's kinda guaranteed to get focused? I just assume that a browser won't emit a click event for an iframe if the parent somehow blocks the click or iframe from getting focus (at least I hope that if so you also get a blur, I say that [because](https://www.reddit.com/r/javascript/comments/6sk46p/blurfocus_events_when_disabling_inputs_browsers/)).

**Comment by samme** [comment]
You can also try

    game.input.onDown.add(game.focusGain, game)

Maybe we could add something like that to Phaser.Stage.

**Comment by samme** [comment]
Also could add a Phaser.Stage#disableBlur option to simply ignore window.onblur events.

**Comment by samme** [comment]
> game.input.onDown.add(game.focusGain, game)

<http://plnkr.co/edit/IywotPVUdY4qIoPa3BmG?p=preview>

**Comment by samme** [comment]
In <http://plnkr.co/edit/CTDk2k8YHNyyYXvIUBev?p=preview> (the original bug example), if you resume the game manually (e.g., `game.paused = false` in the console), you'll find that clicking on the page outside the game canvas no longer pauses the game either. `blur` and `focus` seem to fire no more than once.

**Comment by samme** [comment]
If you still need a workaround (#367), I think the best choices are

```javascript
game.input.mspointer.stop();
```

or

```javascript
game.input.onDown.add(function(pointer, event) {
  game.gameResumed(event);
}, null, 1);
```
