### ISSUE TITLE
worldRotation isn't calculated correctly.

### ISSUE THREAD

**Issue by rgk** [photonstorm/phaser-ce#259]
* A bug in the API:
worldRotation
  * Phaser version(s):
2.8.0
  * Live example:
https://phaser.io/sandbox/edit/mBHEILwq (shows it working on phaser 2.6.2)
My current game located at http://aerialdrop.com/ shows in console when you shoot that the value is off and the same as rotation with phaser-ce 2.8.0
  * What should happen:
World rotation should be different then rotation in situations where parent is also rotated with its child.
  * What happens instead:
They show the same value, thus not properly producing the right worldRotation.

**Comment by samme** [comment]
Probably this will be fixed by 43c93a3a2c795cd81ef4b16ae01793dec39f6853.

Be careful, all the `world*` values are accurate only after `updateTransform` (or at least one game update). In <https://phaser.io/sandbox/edit/mBHEILwq> the `worldRotation` value appears correct during create() only because its initial value (0) happens to be correct. If you try other rotation values, you'll see it's always 0 there.

**Comment by rgk** [comment]
I think the issue might have come from this commit: https://github.com/photonstorm/phaser-ce/commit/c9d69852bc0b87da09488cb70c84f243edda1c62

worldRotation isn't 0, it doesn't represent the worldRotation and only the current rotation of the child and doesn't add the parents rotation also.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/WOxWMJ>
