### ISSUE TITLE
Should we start a new funding system?

### ISSUE THREAD

**Issue by EddieOne** [photonstorm/phaser-ce#275]
Sad to see Phaser 2 die. Should we start a new funding system to pick up the slack? Maybe it would be better to wait or fork first.

![phaserceeeeeee](https://user-images.githubusercontent.com/1835156/27980890-c0d68344-6340-11e7-9212-7bc786192468.jpg)

**Comment by photonstorm** [comment]
Meanwhile, on the actual Phaser repo ...

![commits](https://user-images.githubusercontent.com/164476/28015007-1aa72cee-6566-11e7-8d73-02dc2d161bd4.png)

**Comment by EddieOne** [comment]
I guess this one is officially dead. hopefully phaser 3 is really great when it is finished.

**Comment by samme** [comment]
<https://github.com/photonstorm/phaser-ce/graphs/contributors>

**Comment by photonstorm** [comment]
No, neither of them are dead in the slightest. This one is called CE for a reason - because it's maintained by the Community, and samme and co are doing an amazing job with it. The main Phaser repo is now dedicated to v3 development, and we're doing an equally massive amount of work over there too. Nothing is dead, quite the opposite. I don't think there has been this much parallel development going on in Phaser's life, ever.

**Comment by EddieOne** [comment]
ah ok, I jumped the gun then. Let's close this, we could always come back to the idea if needed. Just don't want to see Phaser disappear into obscurity, kind of seemed like that at first.

**Comment by photonstorm** [comment]
Do you @EddieOne subscribe to the Phaser World newsletter at all? It contains weekly Dev Logs and is a good heartbeat indicator for the project as a whole.
