### ISSUE TITLE
Update TypeScript docs

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#292]
- We added `types` to package.json (#276). I don't know how that change affects a Phaser–TypeScript project.
- Most Phaser–TypeScript project templates link to Phaser's definitions in a [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file (`files`, `include`).
- The [TypeScript README](https://github.com/photonstorm/phaser-ce/blob/master/typescript/README.md) recommends `typings install`.
- The [TypeScript tutorial](http://www.gamefromscratch.com/page/Adventures-in-Phaser-with-TypeScript-tutorial-series.aspx) linked from [README](https://github.com/photonstorm/phaser-ce/blob/master/README.md#getting-started) is a few years old.

Suggestions?

**Comment by Majirefy** [comment]
I use TypeScript in Visual Studio Code.

I do nothing but `npm install`, then `npm init', then `tsc --init` then `tslint --init`. Everything works fine in VS Code. I don't think there is need to modify TypeScript for using `types`.

Or we can just publish phaser.comment.d.ts to `types`. Then we can manually add by using `npm install @types/phaserjs` like this.

**Comment by Dreaded-Gnu** [comment]
For the ionic template project I've just installed phaser-ce as additional dependency without using typings. Code completion within visual studio code worked out of the box. So when it works generally without `typings`, we could remove the typescript readme and add a simple typescript project template.  

I think that it worked out of the box was because of the behaviour of typescript compiler to scan `node_modules` dependencies, when trying to import some module. You need `typings` or the `@types` package only for that reason, that a project has generally no typescript definition file ( plain javascript project ) or when the typescript definition files hasn't been added to package.json correctly, as it was previously. For example sequelizejs is a plain nodejs javascript orm with a extra repository containing typescript definition files ( installed via typings ).

I'll try to migrate a personal typescript game project currently using legacy phaser as dependency to phaser-ce without using `typings`. I'll post the result of that try here.

**Comment by samme** [comment]
Upshot:

- Since [v2.8.2](https://github.com/photonstorm/phaser-ce/releases/tag/v2.8.2) NPM-installed Phaser CE's definitions should be found automatically.
- For Phaser CE before 2.8.2 or installed without NPM, you can
  - Link to Phaser's definitions in tsconfig.json; or
  - Use `typings` (??)
- [Selecting Phaser's definition files in your editor](https://phaser.io/tutorials/how-to-use-phaser-with-typescript) is probably unnecessary.

**Comment by omenking** [comment]
Having lots of pain getting types to show up in VSCode.

I'm uncertain about `typings` and see more of `@types` do we simply need it add our types to definitelytyped? 
```ts
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "lib": ["es2015","es6","es7"],
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "main/*"       : ["src/main/*"],
      "components/*" : ["src/renderer/components/*"],
      "core/*"       : ["src/renderer/core/*"],
      "states/*"     : ["src/renderer/states/*"],
      "ui/*"         : ["src/renderer/ui/*"],
      "common/*"     : ["src/common/*"],
      "devtools_components/*" : ["src/devtools/components/*"],
      "devtools_common/*" : ["src/devtools/common/*"]
    }
  },
  "include": [
    "./src/*",
    "./node_modules/phaser-ce/typescript/pixi.comments.d.ts" ,
    "./node_modules/phaser-ce/typescript/p2.d.ts",
    "./node_modules/phaser-ce/typescript/phaser.comments.d.ts" 
  ],
  "exclude": [
    "dist",
    "app"
  ]
}
```
