### ISSUE TITLE
Incorrect mouse down states related to holding of multiple mouse buttons (Chrome & Brave)

### ISSUE THREAD

**Issue by DivineOmega** [photonstorm/phaser-ce#293]
This issue is about:

* A bug in the API:
  * Phaser version(s): 2.8.2
  * Live example: https://codepen.io/anon/pen/mMdedZ
  * What should happen: Mouse button down states should register correctly regardless of whether buttons are held simultaneously.
  * What happens instead: Holding one mouse button, then the other, then releasing one and then the other, causes a number of incorrect mouse button down states. This occurs in the latest version of Chrome and Brave at time of typing. See the 'Steps to reproduce for more details.
  * Steps to reproduce:

In Chrome (59.0.3071.115) or Brave (0.17.19), open the live example URL, click 'Run', and perform the following steps.

1. Hold down the left mouse button in the canvas.
2. While still holding the left mouse button, hold the right mouse button. **Note that the 'Right Button' does not show as true.**
3. Release the left mouse button, keeping the right mouse button held. **Note that the 'Right Button' does not show as false.**
4. Release the right mouse button. **Note that the 'Left Button' remains as true.**

Note that these steps can also be performed with right mouse button being held first. Similar issues occur.

Although I'd imagine it is unlikely this is a platform specific issue, I'm running the browsers on Ubuntu 16.04. It may also be worth noting that the issue does not appear to occur at all in Firefox.

**Comment by samme** [comment]
Can you try with `game.input.mspointer.enabled = false`?

**Comment by samme** [comment]
<https://codepen.io/samme/pen/brGVqw>

**Comment by DivineOmega** [comment]
@samme I've tried added `game.input.mspointer.enabled = false` to the `create` method of my test, but it seems to prevent any mouse down checks from working.

**Comment by samme** [comment]
How about `game.input.mouse.enabled = false`?

**Comment by DivineOmega** [comment]
@samme Adding `game.input.mouse.enabled = false` to the `create` method seems to have no effect on this issue.

**Comment by samme** [comment]
Does **input.mouse.event** `button` look correct during `mouseup` and `mousedown` in <https://codepen.io/samme/pen/brGVqw>?

**Comment by DivineOmega** [comment]
The `input.mouse.event` section looks like the following and does now change when mouse buttons are clicked.

```
input.mouse.event
button: 0
type: mousemove
```

**Comment by DivineOmega** [comment]
Is anyone able to replicate this issue?

**Comment by samme** [comment]
I had to switch mice, but I think I did.

I tried `monitorEvents(game.canvas, 'pointer')` in Chrome's console and then did left-down, right-down, left-up, right-up. The events seem to be

1. `pointerdown button=0`
2. `pointermove button=2`
3. `pointermove button=0`
4. `pointerup   button=2`

Afterwards both `input.isDown` and `leftButton.isDown` are true (incorrect).

In that case I think Phaser is confused (rightly) because the `pointerup` and `pointerdown` buttons don't match.

But when I do left-down, right-down, right-up, left-up, both `isDown` properties are false (correct) afterwards.

**Comment by samme** [comment]
A workaround:

    game.input.mspointer.stop()

**Comment by TheCell** [comment]
Can you confirm that the example here https://phaser.io/examples/v2/input/mouse-buttons#gv works? If I try that online it does work, if I copy your example or that online example and run it in my own html file it does not work.

**Comment by samme** [comment]
@TheCell doesn't work how?

**Comment by TheCell** [comment]
by doesn't work I meant that the same issue appears as the example @DivineOmega described. It has incorrect states when following the described process. But that only happens when I create my own html and paste the code into it.

**Comment by samme** [comment]
<https://phaser.io/examples/v2/input/mouse-buttons> is running Phaser v2.6.2, which won't show this issue (I think) because it doesn't use Chrome's Pointer Events.

In Phaser CE, you should be able to add `game.input.mspointer.stop()` in your init/create call to avoid the issue.

**Comment by DivineOmega** [comment]
I can confirm @samme's work around also works for me.

**Comment by samme** [comment]
If anyone has IE or Edge, please check if they also record a `pointermove` during the same button sequence (left-down, right-down, left-up, right-up).

<https://codepen.io/samme/pen/brGVqw>

**Comment by TheCell** [comment]
I checked this on Internet Explorer 11 (Update Version: 11.0.44) and it behaves the same as in chrome:
pointerdown, pointermove, pointermove, pointerup

**Comment by 2called-chaos** [comment]
I think pointerevents in chrome are a little bit buggy.

I used a blank page with these listeners:

```js
window.addEventListener("contextmenu", function(ev) { ev.preventDefault() });
window.addEventListener("mouseup", function(ev) { console.log("mouseup", ev.buttons, ev); });
window.addEventListener("mousedown", function(ev) { console.log("mousedown", ev.buttons, ev); });
window.addEventListener("pointerup", function(ev) { ev.preventDefault(); console.log("pointerup", ev.buttons, ev); });
window.addEventListener("pointerdown", function(ev) { ev.preventDefault(); console.log("pointerdown", ev.buttons, ev); });
```

If you hold left you get pointerdown, if you then press any other button no events are fired. Just if you release all buttons at once you will get a pointerup. Now that might be intended (even though it would kinda defeat the purpose of the pointer events imho).

What is funny though: Even though the event listener on pointerdown/up doesn't get called again, no mouse events are fired either so the mouse events do get stopped somehow (it must be the browser because if I don't preventDefault the pointer events I always get mouse events inbetween pointerdown/up).

But if you get a little bit funny and randomly keep pressing mouse button combinations (I just used left and right) then this might happen:

![screen](http://i.imgur.com/HvUPXmJ.png)

This happens way faster in phaser due to JS work being done(?) but I can "glitch it" consistently.

What the screenshot says:

* I spammed combinations for like 50 events than it happened
* Pointer sees me rightclicking (buttons 2 - right)
* A mousedown fires recognizing that I'm now pressing both buttons (buttons 3 - left+right)
* I now get mousedown events as long as I keep one mouse button pressed
* Once all buttons are released the pointerup events fires and THEN we still get a mouseup event with buttons == 0 but this event clearly should have been stopped by my callback


You can (or I can at least) reproduce it with the latest pen from samme, hold left, then spam right and at some point mouse events start firing changing the state of the buttons correctly (or rather so)

**Comment by samme** [comment]
Maybe [Phaser.Pointer#move](https://photonstorm.github.io/phaser-ce/Phaser.Pointer.html#move) fromClick=false can call [Phaser.Pointer.html#updateButtons](https://photonstorm.github.io/phaser-ce/Phaser.Pointer.html#updateButtons) as well.

**Comment by 2called-chaos** [comment]
@samme I tested in chrome on windows and you indeed get pointermove events for changes in buttons, even if you don't actually change the position of the mouse.

Can someone confirm this for IE too? Because it's not noted in the specs it just says "This event is fired when a pointer changes coordinates."

I created a fix that works for me in chrome on windows + it fixes #250 as well. Note that my fix also incorporates #318 and I had to add a new function (and I added one to remove huge if/else in that new required function).

* You can check samme's pen with my patched phaser on https://codepen.io/anon/pen/KvvXXe
* Here's the patched JS: https://gs.breitzeit.de/phaser/builds/phaser-fix_mopm_i293.js
* Here's the commit (don't forget #318): https://github.com/2called-chaos/phaser-ce/commit/e7b6e1f1e06b7e591de08b29569a3d6fdf995bff

**Comment by samme** [comment]
@2called-chaos You can make a PR if it's ready, just make sure you test in a non-Chrome too. We can always rename new functions later, don't worry about that.

**Comment by 2called-chaos** [comment]
@samme I discovered one issue with this approach and that is CTRL+click = rightclick. It registers still as rightclick but as soon as you move the mouse it stops right and starts left. I'm not sure if we can do anything about that. Otherwise it works for me in Chrome, Firefox and IE11.

But generally I don't really know what we want at the end. I have change quite a bit in how buttons are being processed which includes:

* ctrl+click now is detected before buttons are started (ctrl+click now only triggers right and not left button, before it triggered both)
* Mouse events without buttons property fallback to the singular button property (I guess how it was before buttons were introduced) which means that (OSX?) Safari users now can do right/middle click if they have a normal mouse. They now can also use ctrl+click which wasn't possible before because the check was only checking on `buttons === 1` which is undefined. If there is no browser that neither has `event.buttons` nor `event.button` I could also remove the old fallback solution (if event down == left down else everything up).

For the fallback behaviour of `event.button` I reintroduced the old up and down methods and basically did the opposite of my PR #318 so that the are only there for when there is no `event.buttons`. The rest is handled by my newly introduced function.

So basically the question is: can we live with the ctrl+click fact? I mean it wasn't working properly before (right got stuck). In return we get rid of the state issues and increase support for browsers that don't have `event.buttons`.

[Codepen with latest build](https://codepen.io/anon/pen/BdmovO)
[My changes](https://github.com/2called-chaos/phaser-ce/compare/master...fix_mspointer)

One issue I yet have to understand: In my patched version (with Chrome or any mspointer supported browser), if you hold-click and the mouseout it will not revert activePointer state anymore (it will once you let the mouse button go). I'm not sure why this stopped working, is there any other point than [Mouse#onMouseOutGlobal](https://github.com/photonstorm/phaser-ce/blob/master/src/input/Mouse.js#L414-L442) that does this? If not I don't understand why it worked before (in mspointer).

**Comment by samme** [comment]
@2called-chaos As long as there are no serious bugs, you can go ahead and open a PR for it (it's fine if work is ongoing) and we can work on it there.

The ctrl-click situation sounds OK.

Yes, `event.button` is **only** for `mousedown`/`mouseup`, and for `mouseup`, `event.button` indicates the button that was released whereas `event.buttons` doesn't.

I don't know the onMouseOutGlobal behavior very well yet so I'm not sure about that part.

**Comment by 2called-chaos** [comment]
@samme Just working on the PR and I ask myself what is prefered, small functions and more of it (you know I come from a ruby world, small functions, expressive names) or larger functions (like the processButtonsUpDown is quite large). I don't know about the "performance issue" function calls might have.

**Comment by samme** [comment]
@2called-chaos Do as you prefer. I don't think small/several functions would cause a performance problem except in intensive loops.
