### ISSUE TITLE
Arcade rectangle body collision not working properly while dragging

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser-ce#325]
This Issue is about input drag enabled and arcade collision with rectangular vs circular bodies

* A bug in the API:
  * Phaser version(s): 2.6.1 or older to 2.8.4
  * Live example:
https://codepen.io/anon/pen/MvrNbN?editors=0010#0
  See code below
  * What should happen:
ARCADE Physics
Dragging a rectangle body and colliding with another rectangle should push the colliding rectangle body
  * What happens instead:
Only works with circle body vs rectangle body (only when edges collide with circle) or circle body vs circle body (always)
Never works with rectangle body vs rectangle body

**Comment by samme** [comment]
Strange as it sounds, I think it's the rectangular vs. rectangular behavior that's correct, because when both bodies have zero velocity it marks them [embedded](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.Body.html#embedded) and doesn't separate or bounce them: <https://codepen.io/samme/pen/mMXbmo>

I don't know why the circular ones don't act the same. 

You may be able to get the pushing effect by using `body.moves=false` on the body of the draggable sprite: <https://codepen.io/samme/pen/zdRYZy>

**Comment by fyyyyy** [comment]
Thank you, its precisely what i needed !
