### ISSUE TITLE
In WEBGL renderer, the mask on a group does not work if group.getBounds() is invoked

### ISSUE THREAD

**Issue by mindcity** [photonstorm/phaser-ce#334]
This Issue is about A bug in the API PIXI.DisplayObjectContainer.prototype.getBounds()

In Phaser.WEBGL renderer, the mask on a group does not work if group.getBounds() invoked
but it still works if you use Phaser.CANVAS renderer

please see online example:
https://phaser.io/sandbox/edit/ogYiKNXF

FYI: This issue is found when I try to use alignIn() to align a group with a mask inside, but the mask does not work. (because the method alignIn() invokes the getBounds() )

**Comment by jbpuryear** [comment]
I found a couple ways to fix this. I'm not sure why they work, but here's my guess.

If you add `group.mask.dirty = true` after the call to mask.getBounds the mask works again. I think this is because you're not supposed to add the mask to the group that it acts on.

In the example the mask is created with `group.mask = game.add.graphics(0, 0, group)`, which makes it a mask, but also adds it as a child of the group. Because of this, when you call getBounds on the group it also calls getBounds on the mask, which is setting the mask's dirty flag to false and keeping it from working like it's supposed to.

So the better fix is changing `game.add.graphics(0, 0, group)` to `game.add.graphics(0, 0)`. 

I don't think this is a bug.  Masks just aren't meant to go on the display list.

**Comment by mindcity** [comment]
It works, thanks, @jbpuryear

**Comment by samme** [comment]
Didn't notice that, thanks.

**Comment by griever989** [comment]
So I have a mask which I want to position at the same place as a sprite. I call the following:
```
game.world.add(sprite);
game.world.add(mask);
sprite.mask = mask;
```
and it works fine, until anywhere else in code calls `game.stage.getBounds()`, at which point the mask stops working.

I think it's the same issue as expressed here. Is this still working as intended? Is there something wrong with the above that I am doing? I tried not adding the mask to the world but then I can't figure out how I would position it in the same spot as my other sprite. I also tried adding the mask as a child to a container that also has the masked sprite in it but that also has the same problem (they are still ultimately children of a stage, so the call to `getBounds()` on stage causes the issue).

Any ideas? Thanks!

**Comment by samme** [comment]
It looks like masks are supposed to be in the display list, probably in `game.world`, as in [sprites/mask](https://samme.github.io/phaser-examples-mirror/sprites/mask.html).

If you have to use Stage#getBounds(), I guess you could mark the mask dirty each time.

I'd guess the 

> Return an empty object if the item is a mask!

block is never run because AFAIK Phaser never marks masks as non-renderable.

@griever989 I opened [sprites/mask](https://samme.github.io/phaser-examples-mirror/sprites/mask.html) and ran `game.stage.getBounds()` in the console, and it didn't seem to break the mask. Maybe that's not exactly the same as your situation, though.

**Comment by samme** [comment]
I would favor making the change in https://github.com/photonstorm/phaser-ce/issues/334#issuecomment-354564376 for v2.11.0 (https://codepen.io/samme/pen/aGoKpK). It may change the effects of some existing code, since masks will no longer be included in bounds calculations. Oddly, `renderable` doesn't seem to affect Graphics objects at all, so maybe that should change too.

@Robominister did you try setting `mask.dirty` after any bounds calculations (https://codepen.io/samme/pen/KRPRwL)? Reading the `width` or `height` of any Display Container (stage/world/group) implies a getBounds() call.

**Comment by Robominister** [comment]
@samme 
Thank you for the feedback and example. I will take a  In the end, i removed all calls to width / height, and did some scaling manually, which solved the issue i was having. I will look at the mask.dirty option in the future.

We were trying to add tweens of the scale (or width / height) properties on the masked object, so if doing that, it looks like we might have to set dirty manually in an update function (as in your example) ? (Although we are using TimelineMax, i dont know off the top of my head if it actually reads the properties that it is tweening on an object during the tweens update).
