### ISSUE TITLE
Chrome 55 now requires audio to be unlocked by user gestures, fails playing audio on Android in iframe

### ISSUE THREAD

**Issue by bobonthenet** [photonstorm/phaser-ce#37]
This issue was added to the Phaser repo but I didn't see it here. It also occurs with apk files created with cocoonjs. The workaround in the Phaser issue below worked for me. Details and workaround are in the link below.

https://github.com/photonstorm/phaser/issues/2913

**Comment by NeoHoffa** [comment]
I confirm this happens with the latest build on Android when played through an iframe. I tried the workaround given in [photonstorm/phaser#2913](https://github.com/photonstorm/phaser/issues/2913) which didn't work.

**Comment by AleBles** [comment]
I can fix this but right now I'm doubting between two options. Due to #71 we don't use touch events anymore for chrome but Phaser.Touch contains the logic setup for unlocking audio. Ideally I'd like to patch that, but that would mean we disable Pointer events for chrome and move back too Touch events.

The other option is to port the touch unlock code to the Pointer event (or write something generic) but I'd like to know which solution you guys prefer and way.

Any toughts on this @samme ?

**Comment by samme** [comment]
I favor keeping Pointer Events if we can (but #32 needs to be fixed too).

So option 2, maybe a generic that handle either event type? It could be moved into Phaser.Input or a (tiny) new class, Phaser.TouchLock.
