### ISSUE TITLE
Is there a reason that pre/postUpdate run on killed entities?

### ISSUE THREAD

**Issue by goldfire** [photonstorm/phaser-ce#386]
Commit 4d1d27f3d40b0cf7809fa39dae835a442f897763 added the `updateOnlyExistingChildren` flag to groups, which blocks running the update loop on entities that have `exists = false`. However, it seems that `preUpdate` and `postUpdate` still call on all of these children. Disabling those didn't seem to have an impact that I could tell. Is there something I am overlooking as to why these still need to run?

**Comment by samme** [comment]
I'm not sure. I've also disabled those without any apparent effect.

Component.Core.preUpdate itself exits early for `exists=false` **or** `parent.exists=false`. For all objects it handles `pendingDestroy` and updates `previousPosition` and `previousRotation`.

It sort of makes sense that `pendingDestroy` should work even on killed objects.

Component.Core.postUpdate handles `customRender` regardless of the `exists` value. It also calls postUpdate on any children. Some display objects (BitmapText, Graphics, TilemapLayer) have special postUpdate methods.

Component.PhysicsBody.postUpdate skips nonexisting objects.

**Comment by goldfire** [comment]
Hmm, okay so it wouldn't make sense to just use `updateOnlyExistingChildren` the same on post/pre I suppose? Would it then make sense to add a different flag? We've done further testing and at least with our setup can't find any issues when modifying to use `updateOnlyExistingChildren` on pre/post, and we get ~25% decrease in tick time since we have hundreds of dead entities in groups waiting to be recycled.

**Comment by samme** [comment]
I guess there's no harm in adding `preUpdateOnlyExistingChildren` and `postUpdateOnlyExistingChildren`, though I wish I could describe the consequences better. It feel like `pendingDestroy` should be handled in any case, so that part would have to be moved.

On the other hand, anyone interested enough could just overwrite these methods like you and I have.

I'm curious, do you know where most of that extra/wasted time is spent?
