### ISSUE TITLE
Audiosprite not working on iOS

### ISSUE THREAD

**Issue by myrik** [photonstorm/phaser-ce#485]
* A bug in the API:
  * Phaser version(s): 2.6.2 (also seems to happen in my own game using 2.10.0)
  * Live example: http://phaser.io/examples/v2/audio/audio-sprite
  * What should happen: Sound should play when the buttons are hit
  * What happens instead: Sound doesn't play

Tried on an iPad running iOS 11.2.6 on both Chrome and Safari browsers.

**Comment by squaresun** [comment]
The audio source format used in the example is ```ogg```, which is not supported by iOS browsers.

https://github.com/photonstorm/phaser-examples/blob/39372a8a49dd542496612f4f7611b15be458dc26/examples/audio/audio%20sprite.js#L12

You can test by rewriting ```ogg``` to ```mp3``` and see the result.

BTW I recommend you to use v2.10.1 since there is a bug fix for AudioSprite on ```resume()```

**Comment by samme** [comment]
<https://samme.github.io/phaser-examples-mirror/audio/audio%20sprite.html> as well?

What does <https://codepen.io/samme/pen/PELLvm> show?

**Comment by samme** [comment]
Here's an mp3 examples: <https://samme.github.io/phaser-examples-mirror/audio/pause%20and%20resume.html>.

**Comment by myrik** [comment]
@squaresun You are correct! I switched my game to using mp3 and all is well. Thanks for your help!

@samme The first link did not work for me, but the others played audio fine.
