### ISSUE TITLE
TilemapLayer from Tilemap

### ISSUE THREAD

**Issue by HaoboZ** [photonstorm/phaser-ce#503]
* A problem with my own code

Is there any way to grab out a TilemapLayer from a Tilemap object once the layer has already been created? The object reference to layer and layers in Tilemap are not actual TilemapLayer classes, just objects, and can't be used for collision or getting tiles. The examples only show storing the return value of createLayer and using that, but that just adds the need to manage all the TilemapLayers that are created. 

It seems like it may be a problem with the API as well since the type of Tilemap.layer is number | string | Phaser.TilemapLayer but the value is a regular object?

**Comment by HaoboZ** [comment]
It seems like it may be a problem with the API as well since the type of Tilemap.layer is number | string | Phaser.TilemapLayer but the value is a regular object?

**Comment by samme** [comment]
No, Tilemap doesn't store any layers you create, it leaves that up to you. You could add them all to a Group to manage them collectively. Or store them in your own index.

TilemapLayer has to be used for collision checks and such because it has properties (position, scale) that aren't in the original tilemap data.

- The `layer` argument permits multiple types because there's several ways to reference a layer.
- Tilemap#getLayer always returns an object.
- TilemapLayer#index is always a number.
- TilemapLayer#layer is always an object.
